# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-09-19 19:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='field',
            name='series_id',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
