# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-10-12 12:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_distribution_periodicity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dataset',
            name='title',
        ),
        migrations.RemoveField(
            model_name='distribution',
            name='title',
        ),
        migrations.RemoveField(
            model_name='field',
            name='title',
        ),
        migrations.AddField(
            model_name='dataset',
            name='identifier',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='distribution',
            name='identifier',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
