# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-10-19 01:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_field_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distribution',
            name='download_url',
            field=models.URLField(max_length=1024),
        ),
    ]
