# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-29 13:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Query',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ids', models.CharField(max_length=2000)),
                ('args', models.CharField(max_length=2000)),
                ('timestamp', models.DateTimeField()),
                ('ip_address', models.CharField(max_length=200, null=True)),
                ('params', models.TextField()),
            ],
        ),
    ]
