# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-08 15:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_node'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Node',
        ),
    ]
