# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-17 13:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0003_delete_node'),
    ]

    operations = [
        migrations.AlterField(
            model_name='query',
            name='args',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='query',
            name='ids',
            field=models.TextField(),
        ),
    ]
