# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-06-08 18:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0005_importconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsImportTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('running', 'Corriendo'), ('finished', 'Finalizada')], max_length=64)),
                ('logs', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField()),
            ],
        ),
    ]
