# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-06-19 19:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0006_analyticsimporttask'),
    ]

    operations = [
        migrations.AddField(
            model_name='query',
            name='api_mgmt_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
