# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-08-23 17:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0008_auto_20180725_1114_squashed_0009_query_uri'),
    ]

    operations = [
        migrations.AddField(
            model_name='importconfig',
            name='last_cursor',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
