# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-11-29 15:47
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0009_importconfig_last_cursor'),
    ]

    operations = [
        migrations.AddField(
            model_name='importconfig',
            name='time',
            field=models.TimeField(default=datetime.time(0, 0), help_text='Los segundos serán ignorados'),
        ),
    ]
