# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-01-23 18:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0010_importconfig_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='analyticsimporttask',
            options={'verbose_name': 'Corrida de importación de analytics', 'verbose_name_plural': 'Corridas de importación de analytics'},
        ),
        migrations.AlterModelOptions(
            name='importconfig',
            options={'verbose_name': 'Configuración de importación de analytics'},
        ),
        migrations.AlterModelOptions(
            name='query',
            options={'verbose_name_plural': 'Tabla consultas'},
        ),
    ]
