# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-01-24 14:17
from __future__ import unicode_literals

import builtins
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0011_auto_20190123_1530'),
    ]

    operations = [
        migrations.RenameField(
            model_name='analyticsimporttask',
            old_name='timestamp',
            new_name='created'
        ),
        migrations.AlterField(
            model_name='analyticsimporttask',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='analyticsimporttask',
            name='finished',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='analyticsimporttask',
            name='logs',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='analyticsimporttask',
            name='status',
            field=models.CharField(choices=[('RUNNING', 'Procesando catálogos'), ('FINISHED', 'Finalizada')], max_length=20),
        ),
    ]
