# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-02-08 18:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0012_auto_20190124_1117'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='importconfig',
            name='time',
        ),
    ]
