# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-02-20 14:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0013_remove_importconfig_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='HitsIndicator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serie_id', models.CharField(max_length=64)),
                ('date', models.DateField()),
                ('hits', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Consultas por día de serie',
                'verbose_name_plural': 'Consultas por día de series',
            },
        ),
        migrations.AlterUniqueTogether(
            name='hitsindicator',
            unique_together=set([('serie_id', 'date')]),
        ),
    ]
