# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-04-08 12:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_datajsonar', '0006_synchronizer_node'),
        ('analytics', '0014_auto_20190220_1127'),
    ]

    operations = [
        migrations.AddField(
            model_name='analyticsimporttask',
            name='node',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='django_datajsonar.Node'),
        ),
    ]
