VAGRANTFILE_API_VERSION = "2"

SSH_KEYS = [ '~/.vagrant.d/insecure_private_key', '~/.ssh/id_rsa']

checkout_branch = ENV["CHECKOUT_BRANCH"] || "master"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "bento/ubuntu-16.04"
  config.ssh.private_key_path = SSH_KEYS
  config.ssh.forward_agent = true
  config.ssh.insert_key = false
  config.vm.define "webserver" do |web|
      web.ssh.private_key_path = SSH_KEYS
      web.ssh.forward_agent = true
      web.ssh.insert_key = false
      web.vm.provider :virtualbox do |vb|
        vb.memory = 4096
        vb.cpus = 2
      end
      web.vm.network "private_network", ip: "192.168.35.10"
  end
  config.vm.provision "ansible" do |ansible|
    ansible.compatibility_mode = "2.0"
    ansible.playbook = "site.yml"
    ansible.inventory_path = "inventories/vagrant/hosts"
    
    ansible.verbose = "vvv"
#    ansible.tags = ["elastic"]
    ansible.limit = "all"
    ansible.extra_vars = {
        "checkout_branch" => checkout_branch,
    }
  end
end
