# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-08-22 16:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0001_squashed_0012_metadataconfig_min_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seriesunits',
            name='name',
            field=models.CharField(max_length=300, unique=True),
        ),
    ]
