# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-07-26 19:46
from __future__ import unicode_literals

from django.db import migrations, models
import series_tiempo_ar_api.apps.metadata.models


class Migration(migrations.Migration):

    dependencies = [
        ('django_datajsonar', '0010_auto_20180724_1946'),
        ('metadata', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogAlias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(max_length=100, validators=[series_tiempo_ar_api.apps.metadata.models.validate_not_catalog_id])),
                ('nodes', models.ManyToManyField(blank=True, to='django_datajsonar.Node')),
            ],
        ),
    ]
