# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-08-13 18:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0001_auto_20180810_1220_squashed_0002_auto_20180810_1229'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='catalogalias',
            options={'verbose_name_plural': 'Catalog Aliases'},
        ),
    ]
