# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-11-29 17:10
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0002_auto_20180813_1510'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetadataConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField(default=datetime.time(0, 0), help_text='Los segundos serán ignorados')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
