# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-12-19 15:27
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0003_metadataconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='metadataconfig',
            name='query_config',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={'dataset_description': {'boost': 1},
                                                                          'dataset_source': {'boost': 1},
                                                                          'dataset_title': {'boost': 1},
                                                                          'description': {'boost': 1.5}}),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='indexmetadatatask',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
