# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-01-23 18:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0005_auto_20190111_0958'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='catalogalias',
            options={'verbose_name': 'Catalogs alias', 'verbose_name_plural': 'Catalogs Aliases'},
        ),
        migrations.AlterModelOptions(
            name='indexmetadatatask',
            options={'verbose_name': 'Corrida de indexación de metadatos', 'verbose_name_plural': 'Corridas de indexación de metadatos'},
        ),
        migrations.AlterModelOptions(
            name='metadataconfig',
            options={'verbose_name': 'Configuración de búsqueda de series por metadatos'},
        ),
        migrations.AlterModelOptions(
            name='synonym',
            options={'verbose_name': 'Sinónimo de búsqueda', 'verbose_name_plural': 'Sinónimos de búsqueda'},
        ),
    ]
