# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-03-01 14:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0007_remove_metadataconfig_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeriesUnits',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('percentage', models.BooleanField(default=False)),
            ],
        ),
    ]
