# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-03-01 15:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0008_seriesunits'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seriesunits',
            name='name',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
