# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-04-08 12:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_datajsonar', '0006_synchronizer_node'),
        ('metadata', '0009_auto_20190301_1204'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='seriesunits',
            options={'verbose_name': 'Unidades de serie', 'verbose_name_plural': 'Unidades de series'},
        ),
        migrations.AddField(
            model_name='indexmetadatatask',
            name='node',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='django_datajsonar.Node'),
        ),
    ]
