# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-07-22 14:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0011_auto_20190613_1103'),
    ]

    operations = [
        migrations.AddField(
            model_name='metadataconfig',
            name='min_score',
            field=models.FloatField(default=5),
        ),
    ]
