# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-06-04 14:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CSVDumpTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('RUNNING', 'Procesando catálogos'), ('FINISHED', 'Finalizada')], max_length=20)),
                ('created', models.DateTimeField()),
                ('finished', models.DateTimeField(null=True)),
                ('logs', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DumpFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='dump')),
                ('file_name', models.CharField(choices=[('series-tiempo.csv', 'Valores y metadatos (CSV)'), ('series-tiempo-valores.csv', 'Valores (CSV)'), ('series-tiempo-metadata.csv', 'Metadatos enriquecidos de las series (CSV)'), ('series-tiempo-fuentes.csv', 'Fuentes (CSV)'), ('series-tiempo-csv.zip', 'Valores y metadatos (CSV, zipped)')], max_length=64)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dump.GenerateDumpTask')),
            ],
        ),
    ]
