# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-10-03 20:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dump', '0002_auto_20181003_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dumpfile',
            name='file_type',
            field=models.CharField(choices=[('xlsx', 'XLSX'), ('csv', 'CSV')], default='csv', max_length=12),
        ),
        migrations.AlterField(
            model_name='dumpfile',
            name='node',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='django_datajsonar.Node'),
        ),
    ]
