# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-10-09 17:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dump', '0002_auto_20181003_1735_squashed_0005_auto_20181004_1028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dumpfile',
            name='file_name',
            field=models.CharField(choices=[('series-tiempo', 'Series de tiempo (valores + metadatos)'), ('series-tiempo-valores', 'Series de tiempo (valores)'), ('series-tiempo-metadatos', 'Series de tiempo (metadatos)'), ('series-tiempo-fuentes', 'Series de tiempo (fuentes)')], max_length=64),
        ),
        migrations.AlterField(
            model_name='dumpfile',
            name='file_type',
            field=models.CharField(choices=[('csv', 'CSV'), ('xlsx', 'XLSX'), ('zip', 'ZIP')], default='csv', max_length=12),
        ),
        migrations.RenameModel(
            old_name='CSVDumpTask',
            new_name='GenerateDumpTask',
        ),
        migrations.AddField(
            model_name='generatedumptask',
            name='file_type',
            field=models.CharField(choices=[('csv', 'CSV'), ('xlsx', 'XLSX')], default='CSV', max_length=12),
        ),
    ]
