# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-10-03 20:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dump', '0003_auto_20181003_1736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dumpfile',
            name='node',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='django_datajsonar.Node'),
        ),
    ]
