# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-10-22 15:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dump', '0003_auto_20181009_1131_squashed_0005_generatedumptask_file_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dumpfile',
            name='file_type',
            field=models.CharField(choices=[('csv', 'CSV'), ('xlsx', 'XLSX'), ('zip', 'ZIP'), ('sql', 'SQL')], default='csv', max_length=12),
        ),
    ]
