# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-10-22 16:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dump', '0004_auto_20181022_1237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generatedumptask',
            name='file_type',
            field=models.CharField(choices=[('csv', 'CSV'), ('xlsx', 'XLSX'), ('sql', 'SQL')], default='CSV', max_length=12),
        ),
    ]
