# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-10-04 13:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dump', '0004_auto_20181003_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dumpfile',
            name='file_type',
            field=models.CharField(choices=[('xlsx', 'XLSX'), ('zip', 'ZIP'), ('csv', 'CSV')], default='csv', max_length=12),
        ),
    ]
