# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-11-02 18:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import minio_storage.storage
import series_tiempo_ar_api.apps.dump.models


class Migration(migrations.Migration):

    dependencies = [
        ('dump', '0005_auto_20181022_1304'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZipDumpFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zip_file', models.FileField(storage=minio_storage.storage.MinioMediaStorage(), upload_to=series_tiempo_ar_api.apps.dump.models.zipfile_upload_to)),
                ('dump_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dump.DumpFile')),
            ],
        ),
    ]
