# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-11-02 18:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dump', '0006_zipdumpfile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='zipdumpfile',
            old_name='zip_file',
            new_name='file',
        ),
    ]
