# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-11-29 15:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dump', '0007_auto_20181102_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dumpfile',
            name='file_type',
            field=models.CharField(choices=[('csv', 'CSV'), ('xlsx', 'XLSX'), ('zip', 'ZIP'), ('sqlite', 'SQL'), ('dta', 'DTA')], default='csv', max_length=12),
        ),
        migrations.AlterField(
            model_name='generatedumptask',
            name='file_type',
            field=models.CharField(choices=[('csv', 'CSV'), ('xlsx', 'XLSX'), ('sql', 'SQL'), ('dta', 'DTA')], default='CSV', max_length=12),
        ),
    ]
