# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-06-13 14:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dump', '0011_generatedumptask_node'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generatedumptask',
            name='node',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='django_datajsonar.Node'),
        ),
    ]
