# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-06-13 14:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', 'index_data_task_name_change'),
    ]

    operations = [
        migrations.CreateModel(
            name='APIIndexingConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indexing_timeout', models.IntegerField(default=1000)),
            ],
            options={
                'verbose_name': 'Configuración de rutina de indexación',
            },
        ),
        migrations.AlterField(
            model_name='indexdatatask',
            name='node',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='django_datajsonar.Node'),
        ),
        migrations.AlterField(
            model_name='integrationtesttask',
            name='node',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='django_datajsonar.Node'),
        ),
    ]
