# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-01 15:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', 'read_datajson_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='catalog',
            field=models.TextField(default='{}'),
        ),
    ]
