# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-11-29 15:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', 'reset_crons'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskCron',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField(help_text='Los segundos serán ignorados')),
                ('enabled', models.BooleanField(default=True)),
                ('weekdays_only', models.BooleanField(default=False)),
                ('task_script_path', models.CharField(default=None, max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='IndexingTaskCron',
        ),
    ]
