# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-05-07 18:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', 'py3_empty_failed_queue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indicator',
            name='type',
            field=models.CharField(choices=[('catalogos_nuevos_cant', 'Catálogos nuevos'), ('catalogos_actualizados_cant', 'Catálogos actualizados'), ('catalogos_no_actualizados_cant', 'Catálogos no actualizados'), ('catalogos_cant', 'Catálogos totales'), ('catalogos_error_cant', 'Catálogos con error'), ('datasets_actualizados_cant', 'Datasets actualizados'), ('datasets_no_actualizados_cant', 'Datasets no actualizados'), ('datasets_indexables_discontinuados_cant', 'Datasets indexables (discontinuados)'), ('datasets_indexables_cant', 'Datasets indexables'), ('datasets_error_cant', 'Datasets con errores'), ('datasets_nuevos_cant', 'Datasets no indexables (nuevos)'), ('datasets_no_indexables_anteriores_cant', 'Datasets no indexables (anteriores)'), ('datasets_no_indexables_discontinuados_cant', 'Datasets no indexables (discontinuados)'), ('datasets_no_indexables_cant', 'Datasets no indexables (total)'), ('datasets_disponibles_cant', 'Datasets disponibles'), ('datasets_cant', 'Datasets totales'), ('distribuciones_actualizadas_cant', 'Distribuciones actualizadas'), ('distribuciones_no_actualizadas_cant', 'Distribuciones no actualizadas'), ('distribuciones_indexables_discontinuadas_cant', 'Distribuciones indexables (discontinuadas)'), ('distribuciones_indexables_cant', 'Distribuciones indexables'), ('distribuciones_error_cant', 'Distribuciones con error'), ('distribuciones_nuevas_cant', 'Distribuciones no indexables (nuevas)'), ('distribuciones_no_indexables_anteriores_cant', 'Distribuciones no indexables (anteriores)'), ('distribuciones_no_indexables_discontinuadas_cant', 'Distribuciones no indexables (discontinuadas)'), ('distribuciones_no_indexables_cant', 'Distribuciones no indexables'), ('distribuciones_disponibles_cant', 'Distribuciones disponibles'), ('distribuciones_cant', 'Distribuciones totales'), ('series_actualizadas_cant', 'Series actualizadas'), ('series_no_actualizadas_cant', 'Series no actualizadas'), ('series_indexables_discontinuadas_cant', 'Series indexables (discontinuadas)'), ('series_indexables_cant', 'Series indexables'), ('series_error_cant', 'Series con error'), ('series_nuevas_cant', 'Series no indexables (nuevas)'), ('series_no_indexables_anteriores_cant', 'Series no indexables (anteriores)'), ('series_no_indexables_discontinuadas_cant', 'Series no indexables (discontinuadas)'), ('series_no_indexables_cant', 'Series no indexables'), ('series_disponibles_cant', 'Series disponibles'), ('field_cant', 'Series totales')], max_length=100),
        ),
        migrations.DeleteModel(
            name='BaseRegisterFile',
        ),
        migrations.DeleteModel(
            name='DatasetIndexingFile',
        ),
        migrations.DeleteModel(
            name='NodeRegisterFile',
        ),
    ]
