# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-05-21 17:25
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('django_datajsonar', '0004_auto_20180510_1904'),
        ('management', 'move_to_datajsonar'),
    ]

    operations = [
        migrations.CreateModel(
            name='NodeAdmins',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admins', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
                ('node', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='django_datajsonar.Node')),
            ],
        ),
    ]
