# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-01-11 18:36
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('management', 'integration_test_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntegrationTestConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField(default=datetime.time(5, 0), help_text='Los segundos serán ignorados')),
                ('recipients', models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
