# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-04-08 12:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('django_datajsonar', '0006_synchronizer_node'),
        ('management', 'delete_duplicated_metadata'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ReadDataJsonTask',
            new_name='IndexDataTask',
        ),

        migrations.AddField(
            model_name='IndexDataTask',
            name='node',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to='django_datajsonar.Node'),
        ),

        migrations.AddField(
            model_name='integrationtesttask',
            name='node',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to='django_datajsonar.Node'),
        ),

        migrations.AlterField(
            model_name='indicator',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.IndexDataTask'),
        ),
    ]
