# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-01-11 12:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_auto_20181129_1247'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntegrationTestTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('RUNNING', 'Procesando catálogos'), ('FINISHED', 'Finalizada')], max_length=20)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('finished', models.DateTimeField(null=True)),
                ('logs', models.TextField()),
            ],
            options={
                'verbose_name': 'Corrida de test de integración',
                'verbose_name_plural': 'Corridas de test de integración',
            },
        ),
    ]
