# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-05-10 20:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_auto_20180507_1500'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='readdatajsontask',
            name='catalogs',
        ),
        migrations.AlterField(
            model_name='indicator',
            name='node',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_datajsonar.Node'),
        ),
        migrations.DeleteModel(
            name='Node',
        ),
    ]
