# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-01-11 18:36
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_integrationtestconfig'),
    ]

    operations = [
        migrations.AlterField(
            model_name='integrationtestconfig',
            name='recipients',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
