# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-04 18:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datasetsindexingfile',
            old_name='user',
            new_name='uploader',
        ),
        migrations.AlterField(
            model_name='datasetsindexingfile',
            name='logs',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='datasetsindexingfile',
            name='modified',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='datasetsindexingfile',
            name='state',
            field=models.CharField(choices=[('UPLOADED', 'Cargado'), ('PROCESSING', 'Procesando'), ('PROCESSED', 'Procesado'), ('FAILED', 'Error')], default='UPLOADED', max_length=20),
        ),
    ]
