# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-05-21 17:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_nodeadmins'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nodeadmins',
            options={'verbose_name_plural': 'Node admins'},
        ),
    ]
