# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-10 15:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_auto_20180110_1022'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndexingTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.CharField(choices=[(('MON',), 'Lunes'), (('TUE',), 'Martes'), (('WED',), 'Mi\xe9rcoles'), (('THU',), 'Jueves'), (('FRI',), 'Viernes'), (('SAT',), 'S\xe1bado'), ('SUN', 'Domingo')], max_length=20)),
                ('time', models.TimeField()),
                ('enabled', models.BooleanField(default=True)),
            ],
        ),
    ]
