# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-06 16:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_indicator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='indicator',
            name='name',
        ),
        migrations.AddField(
            model_name='indicator',
            name='type',
            field=models.CharField(choices=[('catalog_new', 'Cat\xe1logos nuevos'), ('catalog_total', 'Cat\xe1logos totales'), ('catalog_updated', 'Cat\xe1logos actualizados'), ('dataset_new', 'Datasets nuevos'), ('dataset_total', 'Datasets totales'), ('dataset_updated', 'Datasets actualizados'), ('distribution_new', 'Distribuciones nuevas'), ('distribution_total', 'Distribuciones totales'), ('distribution_updated', 'Distribuciones actualizadas'), ('field_new', 'Series nuevas'), ('field_total', 'Series totales'), ('field_updated', 'Series actualizadas')], default=None, max_length=100),
            preserve_default=False,
        ),
    ]
