# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-12-17 16:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_integrationtestconfig_timeout'),
    ]

    operations = [
        migrations.CreateModel(
            name='DistributionValidatorConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minimum_values', models.IntegerField(default=2, help_text='Cantidad de observaciones mínimas')),
                ('max_missing_proportion', models.FloatField(default=0.999, help_text='Proporción de valores nulos máximos')),
                ('max_too_small_proportion', models.FloatField(default=0.02, help_text='Proporción de series demasiado pequeñas máximas dentro de una distribución')),
                ('max_field_title_len', models.IntegerField(default=60, help_text='Longitud máxima del título')),
                ('max_null_series_proportion', models.FloatField(default=0.2, help_text='Proporción de valores nulos máximos')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
