# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-01-23 18:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_auto_20190114_1000'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='integrationtestconfig',
            options={'verbose_name': 'Configuración del test de integración'},
        ),
        migrations.AlterModelOptions(
            name='readdatajsontask',
            options={'verbose_name': 'Corrida de indexación de datos', 'verbose_name_plural': 'Corridas de indexación de datos'},
        ),
        migrations.AlterField(
            model_name='integrationtestconfig',
            name='api_endpoint',
            field=models.URLField(help_text='URL completa de la API de series a usar como referencia en los mail de error'),
        ),
    ]
