# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-06 19:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_auto_20180306_1304'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicator',
            name='node',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='management.Node'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='indicator',
            name='value',
            field=models.FloatField(default=0),
        ),
    ]
