# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-10 15:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_indexingtask'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indexingtask',
            name='day_of_week',
            field=models.CharField(choices=[(('MON',), 'Lunes'), (('TUE',), 'Martes'), (('WED',), 'Mi\xe9rcoles'), (('THU',), 'Jueves'), (('FRI',), 'Viernes'), (('SAT',), 'S\xe1bado'), ('SUN', 'Domingo')], max_length=20, null=True),
        ),
    ]
