# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-08-13 18:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_readdatajsontask_indexing_mode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nodeadmins',
            name='admins',
        ),
        migrations.RemoveField(
            model_name='nodeadmins',
            name='node',
        ),
        migrations.DeleteModel(
            name='NodeAdmins',
        ),
    ]
