# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-01-23 18:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_auto_20190123_1530'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='readdatajsontask',
            name='stats',
        ),
        migrations.AlterField(
            model_name='readdatajsontask',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='readdatajsontask',
            name='logs',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='readdatajsontask',
            name='status',
            field=models.CharField(choices=[('RUNNING', 'Procesando catálogos'), ('FINISHED', 'Finalizada')], max_length=20),
        ),
    ]
