# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-19 17:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0006_auto_20180319_0940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indicator',
            name='type',
            field=models.CharField(choices=[('catalog_new', 'Cat\xe1logos nuevos'), ('catalog_total', 'Cat\xe1logos totales'), ('catalog_updated', 'Cat\xe1logos actualizados'), ('dataset_new', 'Datasets nuevos'), ('dataset_total', 'Datasets totales'), ('dataset_updated', 'Datasets actualizados'), ('dataset_not_updated', 'Datasets no actualizados'), ('dataset_indexable', 'Datasets indexables'), ('dataset_not_indexable', 'Datasets no indexables'), ('dataset_error', 'Datasets con errores'), ('distribution_new', 'Distribuciones nuevas'), ('distribution_total', 'Distribuciones totales'), ('distribution_updated', 'Distribuciones actualizadas'), ('distribution_not_updated', 'Distribuciones no actualizadas'), ('distribution_indexable', 'Distribuciones indexables'), ('distribution_not_indexable', 'Distribuciones no indexables'), ('distribution_error', 'Distribuciones con error'), ('field_new', 'Series nuevas'), ('field_total', 'Series totales'), ('field_updated', 'Series actualizadas'), ('field_not_updated', 'Series no actualizadas'), ('field_indexable', 'Series indexables'), ('field_not_indexable', 'Series no indexables'), ('field_error', 'Series con error')], max_length=100),
        ),
    ]
