# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-10 17:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0006_indexingtask_weekdays_only'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReadDataJsonTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('RUNNING', 'Procesando cat\xe1logos'), ('INDEXING', 'Indexando series'), ('FINISHED', 'Finalizada'), ('ERROR', 'Error')], max_length=20)),
                ('created', models.DateTimeField()),
                ('finished', models.DateTimeField(null=True)),
                ('logs', models.TextField(default='-')),
            ],
        ),
        migrations.RemoveField(
            model_name='indexingtask',
            name='day_of_week',
        ),
        migrations.AlterField(
            model_name='indexingtask',
            name='time',
            field=models.TimeField(help_text='Los segundos ser\xe1n ignorados'),
        ),
    ]
