# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-11 16:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_dataset_present'),
        ('management', '0007_auto_20180110_1455'),
    ]

    operations = [
        migrations.AddField(
            model_name='readdatajsontask',
            name='catalogs',
            field=models.ManyToManyField(to='api.Catalog'),
        ),
    ]
