# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-11 17:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0009_auto_20180111_1331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='readdatajsontask',
            name='catalogs',
            field=models.ManyToManyField(blank=True, to='management.Node'),
        ),
    ]
