# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-21 13:35
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('management', '0009_auto_20180321_0946'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='admins',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
