# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-23 12:36
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0010_node_admins'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='admins',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
