# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-11 18:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0010_auto_20180111_1412'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='IndexingTask',
            new_name='IndexingTaskCron',
        ),
    ]
