# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-23 13:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0011_auto_20180323_0936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='catalog_url',
            field=models.URLField(unique=True),
        ),
    ]
