# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-15 17:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0011_auto_20180111_1505'),
    ]

    operations = [
        migrations.AddField(
            model_name='readdatajsontask',
            name='stats',
            field=models.TextField(default='{}'),
        ),
    ]
