# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-04 18:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0013_auto_20180404_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indicator',
            name='type',
            field=models.CharField(choices=[(b'catalogos_nuevos_cant', b'Cat\xc3\xa1logos nuevos'), (b'catalogos_cant', b'Cat\xc3\xa1logos totales'), (b'catalogos_actualizados_cant', b'Cat\xc3\xa1logos actualizados'), (b'catalogos_no_actualizados_cant', b'Cat\xc3\xa1logos no actualizados'), (b'catalogos_error_cant', b'Cat\xc3\xa1logos con error'), (b'datasets_nuevos_cant', b'Datasets nuevos'), (b'datasets_cant', b'Datasets totales'), (b'datasets_actualizados_cant', b'Datasets actualizados'), (b'datasets_no_actualizados_cant', b'Datasets no actualizados'), (b'dataset_indexables_cant', b'Datasets indexables'), (b'datasets_no_indexables_cant', b'Datasets no indexables'), (b'datasets_error_cant', b'Datasets con errores'), (b'distribuciones_nuevas_cant', b'Distribuciones nuevas'), (b'distribuciones_cant', b'Distribuciones totales'), (b'distribuciones_actualizadas_cant', b'Distribuciones actualizadas'), (b'distribuciones_no_actualizadas_cant', b'Distribuciones no actualizadas'), (b'distribuciones_indexables_cant', b'Distribuciones indexables'), (b'distribuciones_no_indexables_cant', b'Distribuciones no indexables'), (b'distribuciones_error_cant', b'Distribuciones con error'), (b'series_nuevas_cant', b'Series nuevas'), (b'field_cant', b'Series totales'), (b'series_actualizadas_cant', b'Series actualizadas'), (b'series_no_actualizadas_cant', b'Series no actualizadas'), (b'series_indexables_cant', b'Series indexables'), (b'series_no_indexables_cant', b'Series no indexables'), (b'series_error_cant', b'Series con error')], max_length=100),
        ),
    ]
