# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-05 18:37
from __future__ import unicode_literals

from django.db import migrations, models

from series_tiempo_ar_api.apps.management.models import Indicator


def clean_duplicates(apps, schema_editor):
    ReadDataJsonTask = apps.get_model('management', 'ReadDataJsonTask')
    db_alias = schema_editor.connection.alias

    tasks = ReadDataJsonTask.objects.using(db_alias).all()

    for task in tasks:
        for indicator_type, _ in Indicator.TYPE_CHOICES:
            indicators = task.indicator_set.filter(type=indicator_type)
            if len(indicators) > 1:
                max_val = max([(indic.value, indic) for indic in indicators])
                indicators.exclude(id=max_val[1].id).delete()

    # Borro indicadores "legacy"
    for indic in Indicator.objects.all():
        if indic.type not in [t[0] for t in Indicator.TYPE_CHOICES]:
            indic.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0014_auto_20180404_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indicator',
            name='type',
            field=models.CharField(choices=[(b'catalogos_nuevos_cant', b'Cat\xc3\xa1logos nuevos'), (b'catalogos_actualizados_cant', b'Cat\xc3\xa1logos actualizados'), (b'catalogos_no_actualizados_cant', b'Cat\xc3\xa1logos no actualizados'), (b'catalogos_cant', b'Cat\xc3\xa1logos totales'), (b'catalogos_error_cant', b'Cat\xc3\xa1logos con error'), (b'datasets_actualizados_cant', b'Datasets actualizados'), (b'datasets_no_actualizados_cant', b'Datasets no actualizados'), (b'datasets_indexables_discontinuados_cant', b'Datasets indexables (discontinuados)'), (b'dataset_indexables_cant', b'Datasets indexables'), (b'datasets_error_cant', b'Datasets con errores'), (b'datasets_nuevos_cant', b'Datasets no indexables (nuevos)'), (b'datasets_no_indexables_anteriores_cant', b'Datasets no indexables (anteriores)'), (b'datasets_no_indexables_discontinuados_cant', b'Datasets no indexables (discontinuados)'), (b'datasets_no_indexables_cant', b'Datasets no indexables (total)'), (b'datasets_disponibles_cant', b'Datasets disponibles'), (b'datasets_cant', b'Datasets totales'), (b'distribuciones_actualizadas_cant', b'Distribuciones actualizadas'), (b'distribuciones_no_actualizadas_cant', b'Distribuciones no actualizadas'), (b'distribuciones_indexables_discontinuadas_cant', b'Distribuciones indexables (discontinuadas)'), (b'distribuciones_indexables_cant', b'Distribuciones indexables'), (b'distribuciones_error_cant', b'Distribuciones con error'), (b'distribuciones_nuevas_cant', b'Distribuciones no indexables (nuevas)'), (b'distribuciones_no_indexables_anteriores_cant', b'Distribuciones no indexables (anteriores)'), (b'distribuciones_no_indexables_discontinuadas_cant', b'Distribuciones no indexables (discontinuadas)'), (b'distribuciones_no_indexables_cant', b'Distribuciones no indexables'), (b'distribuciones_disponibles_cant', b'Distribuciones disponibles'), (b'distribuciones_cant', b'Distribuciones totales'), (b'series_actualizadas_cant', b'Series actualizadas'), (b'series_no_actualizadas_cant', b'Series no actualizadas'), (b'series_indexables_discontinuadas_cant', b'Series indexables (discontinuadas)'), (b'series_indexables_cant', b'Series indexables'), (b'series_error_cant', b'Series con error'), (b'series_nuevas_cant', b'Series no indexables (nuevas)'), (b'series_no_indexables_anteriores_cant', b'Series no indexables (anteriores)'), (b'series_no_indexables_discontinuadas_cant', b'Series no indexables (discontinuadas)'), (b'series_no_indexables_cant', b'Series no indexables'), (b'series_disponibles_cant', b'Series disponibles'), (b'field_cant', b'Series totales')], max_length=100),
        ),
        migrations.RunPython(clean_duplicates),
        migrations.AlterUniqueTogether(
            name='indicator',
            unique_together=set([('type', 'node', 'task')]),
        ),
    ]
