# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-08-02 13:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('api', '0001_initial'), ('api', '0002_field_series_id'), ('api', '0003_auto_20170919_1604'), ('api', '0004_distribution_data_file'), ('api', '0005_auto_20170927_0905'), ('api', '0006_field_title'), ('api', '0007_distribution_periodicity'), ('api', '0008_auto_20171012_0849'), ('api', '0009_field_title'), ('api', '0010_auto_20171018_2141'), ('api', '0011_catalog_identifier'), ('api', '0012_auto_20171121_1431'), ('api', '0013_auto_20171123_0803'), ('api', '0014_query'), ('api', '0015_auto_20171130_0819'), ('api', '0016_query_ip_address'), ('api', '0017_query_params'), ('api', '0018_auto_20171130_1027'), ('api', '0019_field_description'), ('api', '0020_delete_query'), ('api', '0021_dataset_indexable'), ('api', '0022_auto_20180104_1332'), ('api', '0023_dataset_present'), ('api', '0024_auto_20180207_1430'), ('api', '0025_distribution_indexable'), ('api', '0026_auto_20180307_1205'), ('api', '0027_field_error'), ('api', '0028_auto_20180312_1038'), ('api', '0029_auto_20180312_1123'), ('api', '0030_dataset_error'), ('api', '0031_auto_20180404_0926'), ('api', '0032_dataset_available'), ('api', '0033_catalog_error'), ('api', '0034_distribution_error'), ('api', '0035_auto_20180521_1315'), ('api', '0036_auto_20190802_1004')]

    initial = True

    dependencies = [
    ]

    operations = [
    ]
