# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-09-19 20:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_field_series_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalog',
            name='title',
            field=models.CharField(default=0, max_length=2000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dataset',
            name='title',
            field=models.CharField(default=0, max_length=2000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='distribution',
            name='title',
            field=models.CharField(default=0, max_length=2000),
            preserve_default=False,
        ),
    ]
