# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-09-22 15:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20170919_1604'),
    ]

    operations = [
        migrations.AddField(
            model_name='distribution',
            name='data_file',
            field=models.FileField(blank=True, upload_to=b'distribution_raw/'),
        ),
    ]
