# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-09-27 13:05
from __future__ import unicode_literals

from django.db import migrations

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_distribution_data_file'),
    ]

    operations = [
    ]
