# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-09-27 15:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20170927_0905'),
    ]

    operations = [
        migrations.AddField(
            model_name='field',
            name='title',
            field=models.CharField(default=b'', max_length=200),
        ),
    ]
