# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-10-03 20:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_field_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='distribution',
            name='periodicity',
            field=models.CharField(default='R/P1Y', max_length=200),
            preserve_default=False,
        ),
    ]
