# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-21 15:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20171018_2141'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalog',
            name='identifier',
            field=models.CharField(default=b'sspm', max_length=200),
        ),
    ]
