# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-23 13:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20171121_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalog',
            name='identifier',
            field=models.CharField(default=b'sspm', max_length=200, unique=True),
        ),
    ]
