# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-30 12:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20171123_0803'),
    ]

    operations = [
        migrations.CreateModel(
            name='Query',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request', models.CharField(max_length=2000)),
                ('args', models.CharField(max_length=2000)),
                ('timestamp', models.DateTimeField()),
            ],
        ),
    ]
