# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-30 13:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_query'),
    ]

    operations = [
        migrations.RenameField(
            model_name='query',
            old_name='request',
            new_name='ids',
        ),
    ]
