# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-30 15:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_auto_20171130_0819'),
    ]

    operations = [
        migrations.AddField(
            model_name='query',
            name='ip_address',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
