# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-30 15:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_query_ip_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='query',
            name='params',
            field=models.TextField(default={}),
            preserve_default=False,
        ),
    ]
