# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-04 16:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_dataset_indexable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataset',
            name='indexable',
            field=models.BooleanField(default=False),
        ),
    ]
