# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-07 17:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_dataset_present'),
    ]

    operations = [
        migrations.AddField(
            model_name='distribution',
            name='data_hash',
            field=models.CharField(default=b'', max_length=128),
        ),
        migrations.AddField(
            model_name='distribution',
            name='last_updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
