# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-07 18:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_auto_20180207_1430'),
    ]

    operations = [
        migrations.AddField(
            model_name='distribution',
            name='indexable',
            field=models.BooleanField(default=True),
        ),
    ]
