# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-07 15:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_distribution_indexable'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalog',
            name='updated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dataset',
            name='updated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='distribution',
            name='updated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='field',
            name='updated',
            field=models.BooleanField(default=True),
        ),
    ]
