# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-09 18:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_auto_20180307_1205'),
    ]

    operations = [
        migrations.AddField(
            model_name='field',
            name='error',
            field=models.BooleanField(default=False),
        ),
    ]
