# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-12 13:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_field_error'),
    ]

    operations = [
        migrations.AlterField(
            model_name='field',
            name='updated',
            field=models.BooleanField(default=False),
        ),
    ]
