# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-12 14:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_auto_20180312_1038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distribution',
            name='indexable',
            field=models.BooleanField(default=False),
        ),
    ]
