# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-04 12:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_dataset_error'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dataset',
            unique_together=set([('identifier', 'catalog')]),
        ),
    ]
