# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-04 18:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_dataset_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalog',
            name='error',
            field=models.BooleanField(default=False),
        ),
    ]
