# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-08-02 13:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_auto_20180521_1315'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dataset',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='dataset',
            name='catalog',
        ),
        migrations.RemoveField(
            model_name='distribution',
            name='dataset',
        ),
        migrations.RemoveField(
            model_name='field',
            name='distribution',
        ),
        migrations.DeleteModel(
            name='Catalog',
        ),
        migrations.DeleteModel(
            name='Dataset',
        ),
        migrations.DeleteModel(
            name='Distribution',
        ),
        migrations.DeleteModel(
            name='Field',
        ),
    ]
